次のコードがあります。

class MyException extends RuntimeException{}    //1
public class Main {
    static void bar() {                         //4
        foo();
    }
    static void foo() throws MyException {      //7
        throw new MyException();
    }
    public static void main(String[] args) {    //10
        try {
            foo();                              //12
            System.out.println("B");
        } catch (MyException e) {
            bar();                              //15
        } catch (RuntimeException e) {
            System.out.println("C");            //17
        } finally {
            System.out.println("D");            //19
        }
    }
}

コンパイル、実行した結果として正しいものは次のどれですか。
1つ選択してください。

A. BとDが表示される
B. BとC表示される
C. BとCとDが表示される
D. エラーメッセージのみ表示される
E. D.とエラーメッセージが表示される
F. コンパイルエラー
